# Generated by Django 5.0 on 2026-01-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_dari', models.CharField(max_length=100)),
                ('name_pashto', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_dari', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Design Portfolio',
                'verbose_name_plural': 'Design Portfolio',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sleeve', 'Sleeve Style'), ('collar', 'Collar Type'), ('pocket', 'Pocket Style')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('name_dari', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_options/')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_options', to='orders.clothingtype')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('fabric_notes', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready', 'Ready for Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_style', models.CharField(choices=[('simple', 'Simple'), ('open', 'Open'), ('qandahari', 'Qandahari')], max_length=20)),
                ('collar_type', models.CharField(choices=[('circle', 'Circle Collar'), ('shirt', 'Shirt Collar'), ('indian', 'Indian Collar'), ('qasami', 'Qasami Collar')], max_length=20)),
                ('has_front_pocket', models.BooleanField(default=False)),
                ('has_side_pockets', models.BooleanField(default=False)),
                ('skirt_style', models.CharField(choices=[('circle', 'Circle'), ('square', 'Square')], max_length=20)),
                ('pants_style', models.CharField(choices=[('normal', 'Normal'), ('wide', 'Wide'), ('narrow', 'Narrow')], max_length=20)),
                ('has_pants_pocket', models.BooleanField(default=False)),
                ('fabric_color', models.CharField(choices=[('white', 'White'), ('beige', 'Beige'), ('black', 'Black'), ('gray', 'Gray'), ('navy_blue', 'Navy Blue'), ('cream', 'Cream'), ('sky_blue', 'Sky Blue'), ('charcoal', 'Charcoal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asteen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yakhan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chaati', models.DecimalField(decimal_places=2, max_digits=5)),
                ('baghal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daman', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qad_shalwar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pacha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measurement_unit', models.CharField(default='cm', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
