# Generated by Django 5.0 on 2026-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdesign',
            name='fabric_color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Navy Blue', 'Navy Blue'), ('Royal Blue', 'Royal Blue'), ('Brown', 'Brown'), ('Beige', 'Beige'), ('Gray', 'Gray'), ('Cream', 'Cream'), ('Maroon', 'Maroon'), ('Green', 'Green'), ('Olive', 'Olive'), ('Charcoal', 'Charcoal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdesign',
            name='sleeve_style',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Style 2', 'Style 2'), ('Style 3', 'Style 3')], max_length=20),
        ),
    ]
