# Generated by Django 5.0 on 2026-01-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_dari', models.CharField(max_length=100)),
                ('name_pashto', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clothing Type',
                'verbose_name_plural': 'Clothing Types',
            },
        ),
        migrations.CreateModel(
            name='DesignPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_dari', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Design Portfolio',
                'verbose_name_plural': 'Design Portfolio',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sleeve', 'Sleeve Style'), ('collar', 'Collar Type'), ('pocket', 'Pocket Style')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('name_dari', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_options/')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_options', to='designs.clothingtype')),
            ],
            options={
                'verbose_name': 'Design Option',
                'verbose_name_plural': 'Design Options',
                'ordering': ['category', 'name'],
            },
        ),
    ]
